In [30]:
import glob
import os
import pandas as pd
from pathlib import Path
import random
from collections import defaultdict
from urllib.parse import urlparse
from pathlib import PurePosixPath
import shutil

In [2]:
data_path = "..\splits\lunch_dinner\data_correct_lunch_dinner_visible.csv"
data = pd.read_csv(data_path)
data.shape

(699, 33)

In [3]:
data.columns

Index(['sub', 'Carb', 'Protein', 'Fat', 'Fiber', 'Image path', 'Meal Type',
       'Amount Consumed', 'AUC', 'Calories', 'iAUC', 'Baseline_Libre', 'Age',
       'Gender', 'BMI', 'A1c', 'HOMA', 'Insulin', 'TG', 'Cholesterol', 'HDL',
       'Non HDL', 'LDL', 'VLDL', 'CHO/HDL ratio', 'Fasting BG',
       'Correct Nutrition', 'full_image_path', 'PWrapped', 'LogitWrapped',
       'LogitVisible', 'GapWrappedMinusVisible', 'IsWrapped'],
      dtype='object')

In [4]:
data["Amount Consumed"].value_counts(dropna=False)

100.0    439
1.0      104
300.0     22
200.0     22
75.0      21
3.0       16
400.0     12
600.0     11
2.0       11
4.0        7
5.0        6
6.0        4
500.0      4
60.0       4
50.0       3
9.0        2
70.0       2
700.0      2
0.0        2
8.0        1
7.0        1
150.0      1
375.0      1
90.0       1
Name: Amount Consumed, dtype: int64

In [5]:
data.groupby("sub")["Amount Consumed"].describe()

     count        mean         std    min    25%    50%     75%    max
sub
1     13.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
2     18.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
3     18.0   81.666667   20.651164   50.0   60.0   95.0  100.00  100.0
4     28.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
5     18.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
6     19.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
7      9.0  122.222222   44.095855  100.0  100.0  100.0  100.00  200.0
8     17.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
9     17.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
10    14.0   98.214286    6.681531   75.0  100.0  100.0  100.00  100.0
11    16.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
12    16.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
13    17.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
14    20.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
15    16.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
16     5.0    1.000000    0.000000    1.0    1.0    1.0    1.00    1.0
17    17.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
18    18.0    1.444444    0.783823    1.0    1.0    1.0    1.75    3.0
19    19.0    1.526316    0.772328    1.0    1.0    1.0    2.00    3.0
20    15.0    2.666667    2.225395    1.0    1.0    1.0    3.50    8.0
21    17.0    1.823529    1.286239    1.0    1.0    1.0    3.00    5.0
22    15.0    2.266667    1.437591    1.0    1.0    2.0    3.50    5.0
23    22.0    2.772727    2.158743    1.0    1.0    1.5    4.75    7.0
26    15.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
27    17.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
28    17.0    1.000000    0.000000    1.0    1.0    1.0    1.00    1.0
29    17.0    1.000000    0.000000    1.0    1.0    1.0    1.00    1.0
30     7.0    4.142857    3.625308    1.0    1.0    3.0    7.00    9.0
31    10.0  110.000000   31.622777  100.0  100.0  100.0  100.00  200.0
32     8.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
33    13.0  176.923077  132.861746   75.0  100.0  100.0  200.00  500.0
34    25.0  220.000000  189.296945  100.0  100.0  100.0  300.00  700.0
35    10.0  200.000000  176.383421  100.0  100.0  100.0  250.00  600.0
36    11.0  181.818182  107.871978  100.0  100.0  100.0  250.00  400.0
38    11.0  100.000000    0.000000  100.0  100.0  100.0  100.00  100.0
39     8.0  225.000000  190.862703  100.0  100.0  100.0  325.00  600.0
41    14.0  110.714286   55.221830   75.0  100.0  100.0  100.00  300.0
42     6.0   79.166667   18.819316   50.0   75.0   75.0   93.75  100.0
43    36.0  200.000000  162.128697  100.0  100.0  100.0  300.00  600.0
44    19.0  248.684211  201.638029   75.0  100.0  100.0  400.00  600.0
45     9.0  150.000000   92.702481   75.0  100.0  100.0  200.00  300.0
46    15.0  121.666667   62.583278   75.0  100.0  100.0  100.00  300.0
47    16.0  153.125000   84.100634   75.0  100.0  100.0  200.00  300.0
48    16.0  167.187500  131.250000    0.0  100.0  100.0  225.00  500.0
49    15.0  215.000000  207.622597   75.0  100.0  100.0  300.00  700.0

In [6]:
all_data_lunch = data[data["Meal Type"] == "Lunch"]
all_data_lunch.shape

(362, 33)

In [7]:
all_data_dinner = data[data["Meal Type"] == "Dinner"]
all_data_dinner.shape

(337, 33)

In [8]:
all_data_lunch.groupby("sub")["Amount Consumed"].describe()

     count        mean        std    min     25%    50%     75%    max
sub
1      6.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
2      8.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
3     10.0   67.000000  16.363917   50.0   60.00   60.0   70.00  100.0
4     10.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
5      8.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
6      9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
7      6.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
8      9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
9     10.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
10    10.0   97.500000   7.905694   75.0  100.00  100.0  100.00  100.0
11     8.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
12    10.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
13     9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
14     9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
15     7.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
16     5.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
17     9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
18     9.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
19     9.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
20     8.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
21    10.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
22     7.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
23    10.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
26     9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
27    10.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
28     9.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
29     8.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
30     3.0    1.000000   0.000000    1.0    1.00    1.0    1.00    1.0
31     7.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
32     8.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
33     7.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
34     9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
35     7.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
36     6.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
38    10.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
39     5.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
41     7.0   92.857143  12.198751   75.0   87.50  100.0  100.00  100.0
42     6.0   79.166667  18.819316   50.0   75.00   75.0   93.75  100.0
43     9.0  100.000000   0.000000  100.0  100.00  100.0  100.00  100.0
44     9.0   91.666667  12.500000   75.0   75.00  100.0  100.00  100.0
45     6.0   91.666667  12.909944   75.0   81.25  100.0  100.00  100.0
46     7.0   92.857143  12.198751   75.0   87.50  100.0  100.00  100.0
47     7.0   92.857143  12.198751   75.0   87.50  100.0  100.00  100.0
48     7.0   96.428571   9.449112   75.0  100.00  100.0  100.00  100.0
49    10.0   92.500000  12.076147   75.0   81.25  100.0  100.00  100.0

In [9]:
all_data_dinner.groupby("sub")["Amount Consumed"].describe()

     count        mean         std    min     25%    50%     75%    max
sub
1      7.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
2     10.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
3      8.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
4     18.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
5     10.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
6     10.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
7      3.0  166.666667   57.735027  100.0  150.00  200.0  200.00  200.0
8      8.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
9      7.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
10     4.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
11     8.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
12     6.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
13     8.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
14    11.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
15     9.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
17     8.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
18     9.0    1.888889    0.927961    1.0    1.00    2.0    3.00    3.0
19    10.0    2.000000    0.816497    1.0    1.25    2.0    2.75    3.0
20     7.0    4.571429    1.902379    3.0    3.00    4.0    5.50    8.0
21     7.0    3.000000    1.290994    1.0    2.50    3.0    3.50    5.0
22     8.0    3.375000    1.060660    2.0    2.75    3.5    4.00    5.0
23    12.0    4.250000    1.912875    1.0    2.75    4.5    6.00    7.0
26     6.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
27     7.0  100.000000    0.000000  100.0  100.00  100.0  100.00  100.0
28     8.0    1.000000    0.000000    1.0    1.00    1.0    1.00    1.0
29     9.0    1.000000    0.000000    1.0    1.00    1.0    1.00    1.0
30     4.0    6.500000    3.000000    3.0    4.50    7.0    9.00    9.0
31     3.0  133.333333   57.735027  100.0  100.00  100.0  150.00  200.0
33     6.0  266.666667  156.258333   75.0  162.50  250.0  356.25  500.0
34    16.0  287.500000  209.364117  100.0  100.00  250.0  400.00  700.0
35     3.0  433.333333  152.752523  300.0  350.00  400.0  500.00  600.0
36     5.0  280.000000   83.666003  200.0  200.00  300.0  300.00  400.0
38     1.0  100.000000         NaN  100.0  100.00  100.0  100.00  100.0
39     3.0  433.333333  152.752523  300.0  350.00  400.0  500.00  600.0
41     7.0  128.571429   75.592895  100.0  100.00  100.0  100.00  300.0
43    27.0  233.333333  175.411604  100.0  100.00  100.0  300.00  600.0
44    10.0  390.000000  185.292561  100.0  225.00  400.0  575.00  600.0
45     3.0  266.666667   57.735027  200.0  250.00  300.0  300.00  300.0
46     8.0  146.875000   78.419089   75.0  100.00  100.0  200.00  300.0
47     9.0  200.000000   86.602540  100.0  100.00  200.0  300.00  300.0
48     9.0  222.222222  156.347192    0.0  200.00  200.0  300.00  500.0
49     5.0  460.000000  194.935887  200.0  400.00  400.0  600.00  700.0

In [13]:
stats = all_data_dinner.groupby("sub")["Amount Consumed"].describe()
stats_not_100 = stats[(stats["mean"] != 100.0) & (stats["mean"] != 1.0)]
stats_not_100

     count        mean         std    min     25%    50%     75%    max
sub
7      3.0  166.666667   57.735027  100.0  150.00  200.0  200.00  200.0
18     9.0    1.888889    0.927961    1.0    1.00    2.0    3.00    3.0
19    10.0    2.000000    0.816497    1.0    1.25    2.0    2.75    3.0
20     7.0    4.571429    1.902379    3.0    3.00    4.0    5.50    8.0
21     7.0    3.000000    1.290994    1.0    2.50    3.0    3.50    5.0
22     8.0    3.375000    1.060660    2.0    2.75    3.5    4.00    5.0
23    12.0    4.250000    1.912875    1.0    2.75    4.5    6.00    7.0
30     4.0    6.500000    3.000000    3.0    4.50    7.0    9.00    9.0
31     3.0  133.333333   57.735027  100.0  100.00  100.0  150.00  200.0
33     6.0  266.666667  156.258333   75.0  162.50  250.0  356.25  500.0
34    16.0  287.500000  209.364117  100.0  100.00  250.0  400.00  700.0
35     3.0  433.333333  152.752523  300.0  350.00  400.0  500.00  600.0
36     5.0  280.000000   83.666003  200.0  200.00  300.0  300.00  400.0
39     3.0  433.333333  152.752523  300.0  350.00  400.0  500.00  600.0
41     7.0  128.571429   75.592895  100.0  100.00  100.0  100.00  300.0
43    27.0  233.333333  175.411604  100.0  100.00  100.0  300.00  600.0
44    10.0  390.000000  185.292561  100.0  225.00  400.0  575.00  600.0
45     3.0  266.666667   57.735027  200.0  250.00  300.0  300.00  300.0
46     8.0  146.875000   78.419089   75.0  100.00  100.0  200.00  300.0
47     9.0  200.000000   86.602540  100.0  100.00  200.0  300.00  300.0
48     9.0  222.222222  156.347192    0.0  200.00  200.0  300.00  500.0
49     5.0  460.000000  194.935887  200.0  400.00  400.0  600.00  700.0

In [11]:
stats_not_100["count"].sum()

191.0

In [12]:
all_data_dinner.shape[0] - stats_not_100["count"].sum()

146.0

In [21]:
all_data_lunch[(all_data_lunch["Amount Consumed"] != 100.0) & (all_data_lunch["Amount Consumed"] != 1.0)][["sub", "Amount Consumed", "Image path"]]

     sub  Amount Consumed                                    Image path
31     3             50.0    photos/00000005-PHOTO-2020-3-11-12-9-0.jpg
32     3             90.0   photos/00000011-PHOTO-2020-3-12-14-25-0.jpg
34     3             60.0   photos/00000017-PHOTO-2020-3-13-12-33-0.jpg
35     3             60.0   photos/00000023-PHOTO-2020-3-14-13-33-0.jpg
37     3             60.0    photos/00000030-PHOTO-2020-3-15-14-6-0.jpg
39     3             70.0   photos/00000039-PHOTO-2020-3-16-13-32-0.jpg
43     3             60.0   photos/00000052-PHOTO-2020-3-18-13-34-0.jpg
45     3             70.0    photos/00000059-PHOTO-2020-3-19-14-7-0.jpg
47     3             50.0   photos/00000066-PHOTO-2020-3-20-12-45-0.jpg
161   10             75.0   photos/00000024-PHOTO-2020-6-24-11-21-0.jpg
553   41             75.0   photos/00000007-PHOTO-2022-4-26-11-14-0.jpg
562   41             75.0    photos/00000100-PHOTO-2022-5-2-11-25-0.jpg
569   42             75.0   photos/00000027-PHOTO-2025-7-27-11-40-0.jpg
570   42             50.0   photos/00000037-PHOTO-2025-7-29-12-29-0.jpg
571   42             75.0   photos/00000047-PHOTO-2025-7-30-16-25-0.jpg
572   42             75.0    photos/00000072-PHOTO-2025-8-3-17-42-0.jpg
609   44             75.0  photos/00000009-PHOTO-2022-10-17-12-15-0.jpg
616   44             75.0  photos/00000048-PHOTO-2022-10-20-12-31-0.jpg
619   44             75.0  photos/00000086-PHOTO-2022-10-23-10-53-0.jpg
629   45             75.0   photos/00000032-PHOTO-2025-3-28-13-43-0.jpg
632   45             75.0   photos/00000056-PHOTO-2025-3-31-12-33-0.jpg
639   46             75.0    photos/00000022-PHOTO-2025-5-4-11-17-0.jpg
645   46             75.0    photos/00000061-PHOTO-2025-5-7-11-29-0.jpg
652   47             75.0   photos/00000008-PHOTO-2025-10-30-12-4-0.jpg
656   47             75.0   photos/00000027-PHOTO-2025-11-2-11-57-0.jpg
672   48             75.0   photos/00000028-PHOTO-2022-11-17-14-2-0.jpg
684   49             75.0   photos/00000006-PHOTO-2025-5-11-11-52-0.jpg
688   49             75.0    photos/00000038-PHOTO-2025-5-14-12-2-0.jpg
694   49             75.0   photos/00000061-PHOTO-2025-5-17-12-16-0.jpg

In [18]:
all_data_lunch[(all_data_lunch["Amount Consumed"] != 100.0) & (all_data_lunch["Amount Consumed"] != 1.0)][["sub"]].count()

sub    29
dtype: int64

In [20]:
all_data_lunch.shape[0] - 29

333

In [24]:
all_data_lunch.loc[43]

sub                                                                       3
Carb                                                                  160.0
Protein                                                               304.0
Fat                                                                   153.0
Fiber                                                                  26.0
Image path                      photos/00000052-PHOTO-2020-3-18-13-34-0.jpg
Meal Type                                                             Lunch
Amount Consumed                                                        60.0
AUC                                                                 13050.5
Calories                                                              585.0
iAUC                                                             288.563953
Baseline_Libre                                                        106.8
Age                                                                      59
Gender                                                                   -1
BMI                                                                26.94869
A1c                                                                     6.5
HOMA                                                                5.06963
Insulin                                                                17.4
TG                                                                      154
Cholesterol                                                             190
HDL                                                                      74
Non HDL                                                                 116
LDL                                                                      90
VLDL                                                                     31
CHO/HDL ratio                                                           2.6
Fasting BG                                                              118
Correct Nutrition                                                      True
full_image_path           ..\..\CGMacros\CGMacros-003\photos/00000052-PH...
PWrapped                                                           0.000028
LogitWrapped                                                      43.957146
LogitVisible                                                      54.450718
GapWrappedMinusVisible                                            -0.104936
IsWrapped                                                             False
Name: 43, dtype: object

In [25]:
all_data_dinner[all_data_dinner["sub"] == 7]

,sub,Carb,Protein,Fat,Fiber,Image path,Meal Type,Amount Consumed,AUC,Calories,...,VLDL,CHO/HDL ratio,Fasting BG,Correct Nutrition,full_image_path,PWrapped,LogitWrapped,LogitVisible,GapWrappedMinusVisible,IsWrapped
115,7,96.0,160.0,36.0,0.0,photos/00000007-PHOTO-2023-11-3-19-26-0.jpg,Dinner,100.0,8580.0,352.0,...,18,3.0,108,True,..\..\CGMacros\CGMacros-007\photos/00000007-PH...,0.000290,45.072144,53.216843,-0.081447,False
116,7,196.0,160.0,36.0,0.0,photos/00000013-PHOTO-2023-11-4-19-16-0.jpg,Dinner,200.0,11615.0,442.0,...,18,3.0,108,True,..\..\CGMacros\CGMacros-007\photos/00000013-PH...,0.000461,42.615400,50.295980,-0.076806,False
118,7,116.0,116.0,117.0,0.0,photos/00000019-PHOTO-2023-11-5-19-18-0.jpg,Dinner,200.0,6927.0,341.0,...,18,3.0,108,True,..\..\CGMacros\CGMacros-007\photos/00000019-PH...,0.003520,41.471054,47.116695,-0.056456,False

In [26]:
all_data_dinner.loc[118]

sub                                                                       7
Carb                                                                  116.0
Protein                                                               116.0
Fat                                                                   117.0
Fiber                                                                   0.0
Image path                      photos/00000019-PHOTO-2023-11-5-19-18-0.jpg
Meal Type                                                            Dinner
Amount Consumed                                                       200.0
AUC                                                                  6927.0
Calories                                                              341.0
iAUC                                                             1210.21519
Baseline_Libre                                                    50.666667
Age                                                                      66
Gender                                                                   -1
BMI                                                               27.070327
A1c                                                                     5.9
HOMA                                                                   4.24
Insulin                                                                15.9
TG                                                                       92
Cholesterol                                                             128
HDL                                                                      43
Non HDL                                                                  85
LDL                                                                      67
VLDL                                                                     18
CHO/HDL ratio                                                           3.0
Fasting BG                                                              108
Correct Nutrition                                                      True
full_image_path           ..\..\CGMacros\CGMacros-007\photos/00000019-PH...
PWrapped                                                            0.00352
LogitWrapped                                                      41.471054
LogitVisible                                                      47.116695
GapWrappedMinusVisible                                            -0.056456
IsWrapped                                                             False
Name: 118, dtype: object

In [27]:
data_filtered = data[(data["Amount Consumed"] == 100.0) | (data["Amount Consumed"] == 1.0)]

In [28]:
data_filtered.shape

(543, 33)

In [29]:
data_filtered.to_csv('../splits/lunch_dinner/data_all_lunch_dinner_consumed.csv', index=False)

In [43]:
data_filtered = pd.read_csv("../splits/lunch_dinner/data_all_lunch_dinner_consumed.csv")

In [44]:
base_out = Path(r"..\pics_consumed")

for idx, row in data_filtered.iterrows():
    src = Path(row["full_image_path"])

    meal_type = str(row["Meal Type"]).strip().lower()
    sub = str(row["sub"]).strip()

    # keep only lunch and dinner
    if meal_type not in ["lunch", "dinner"]:
        continue

    if not src.exists():
        print(f"Missing file: {src}")
        continue

    dst_folder = base_out / meal_type / sub
    dst_folder.mkdir(parents=True, exist_ok=True)

    dst = dst_folder / src.name

    shutil.copy2(src, dst)

In [47]:
# lunch: 22
# 10: 00000005-PHOTO-2020-6-21-11-47-0
# 12: 00000029-PHOTO-2023-3-1-14-23-0, 00000048-PHOTO-2023-3-4-15-1-0
# 14: 00000005-PHOTO-2023-5-9-11-51-0, 00000028-PHOTO-2023-5-12-12-38-0, 00000058-PHOTO-2023-5-15-11-42-0, 00000090-PHOTO-2023-5-18-12-25-0
# 22: 00000052-PHOTO-2021-4-1-12-35-0, 00000071-PHOTO-2021-4-3-12-29-0, 00000104-PHOTO-2021-4-6-12-20-0
# 23: 00000047-PHOTO-2021-5-10-13-25-0, 00000081-PHOTO-2021-5-14-13-26-0
# 28: 00000005-PHOTO-2023-11-28-12-40-0, 00000036-PHOTO-2023-12-3-12-23-0
# 32: 00000025-PHOTO-2022-1-6-12-47-0
# 33: 00000018-PHOTO-2022-4-17-19-18-0 - empty -> 00000017-PHOTO-2022-4-17-19-18-0
# 34: 00000089-PHOTO-2022-3-7-11-53-0 - half eaten
# 36: 00000010-PHOTO-2022-3-30-12-7-0
# 42: 00000017-PHOTO-2025-7-26-11-27-0
# 44: 00000022-PHOTO-2022-10-18-13-53-0 - empty
# 46: 00000017-PHOTO-2025-5-3-11-47-0 - empty
# 48: 00000087-PHOTO-2022-11-23-13-22-0

In [48]:
# dinner: 17
# 4: 00000053-PHOTO-2023-9-15-20-45-0 - icecream, 00000064-PHOTO-2023-9-16-22-39-0 - icecream, 00000075-PHOTO-2023-9-17-20-2-0 - black (burger)
# 10: 00000008-PHOTO-2020-6-21-18-43-0 - banana
# 11: dinner-PHOTO-2020-10-4-19-0-0 - text
# 14: 00000007-PHOTO-2023-5-9-19-1-0, 00000013-PHOTO-2023-5-10-17-40-0, 00000070-PHOTO-2023-5-16-20-2-0, 00000083-PHOTO-2023-5-17-19-46-0, 
#00000093-PHOTO-2023-5-18-19-11-0
# 17: 00000014-PHOTO-2023-10-11-22-35-0 - chips, 00000047-PHOTO-2023-10-14-18-47-0 - hand
# 26: 00000045-PHOTO-2021-3-31-17-10-0
# 34: 00000103-PHOTO-2022-3-8-17-59-0 - empty
# 43: 00000120-PHOTO-2025-10-21-18-4-0, 00000127-PHOTO-2025-10-21-23-0-0, 00000157-PHOTO-2025-10-23-22-34-0

In [49]:
543 - 22 - 17

504